### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by Vikuliia** [gandy92/blackclue#3]
Hi, I'he installed the module. 

But where is the error "ModuleNotFoundError: No module named 'blackclue'.

I've also some errors during the installation:

pymp4 1.1.0 has requirement construct==2.8.8, but you'll have construct 2.9.45 which is incompatible.
Installing collected packages: construct, pymp4, tdx, clickutil, blackclue
  The script mp4dump.exe is installed in 'C:\Users\...\AppData\Local\Programs\WPy-3670\python-3.6.7.amd64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script blackclue.exe is installed in 'C:\Users\...\AppData\Local\Programs\WPy-3670\python-3.6.7.amd64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed blackclue-1.1.1 clickutil-0.0.5 construct-2.9.45 pymp4-1.1.0 tdx-0.1.7

Thanks

**Comment by hasanniz** [comment]
Getting the same ModuleNotFoundError
```bash
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\blackclue.exe\__main__.py", line 5, in <module>
ModuleNotFoundError: No module named 'blackclue'
```

**Comment by gandy92** [comment]
blackclue.exe sounds like you made an executable from the python script. Maybe the packaging did not include all files. If this is the case, please refer to the packager documentation on how to proceed.
Did you try running the script in one of the usual environments, like cpython?

**Comment by algores** [comment]
Hi Andy, thank you for your work.
I have the same problem with macOS 10.14.6 and Centos 7.6.1810

> [root@vmi211663 httpdocs]# pip install blackclue
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: blackclue in /usr/lib64/python2.7/site-packages (1.1.1)
Requirement already satisfied: clickutil in /usr/lib/python2.7/site-packages (from blackclue) (0.0.5)
Requirement already satisfied: click in /usr/lib64/python2.7/site-packages (from blackclue) (7.0)
Requirement already satisfied: construct in /usr/lib/python2.7/site-packages (from blackclue) (2.9.45)
Requirement already satisfied: pymp4 in /usr/lib/python2.7/site-packages (from blackclue) (1.2.0)
Requirement already satisfied: tdx>=0.0.2 in /usr/lib/python2.7/site-packages (from clickutil->blackclue) (0.1.7)
Requirement already satisfied: pyyaml in /usr/lib64/python2.7/site-packages (from tdx>=0.0.2->clickutil->blackclue) (5.1.2)
Requirement already satisfied: wrapt>=1.10.8 in /usr/lib/python2.7/site-packages (from tdx>=0.0.2->clickutil->blackclue) (1.11.2)
[root@vmi211663 httpdocs]# blackclue -x 20190822_161500_EF.mp4
Traceback (most recent call last):
  File "/usr/bin/blackclue", line 7, in <module>
    from blackclue import dump_cli
ImportError: No module named blackclue
[root@vmi211663 httpdocs]# 

> MacBook-Pro-di-daniele:~ daniele$ python3 -m pip install blackclue
Requirement already satisfied: blackclue in /usr/local/lib/python3.7/site-packages (1.1.1)
Requirement already satisfied: click in /usr/local/lib/python3.7/site-packages (from blackclue) (7.0)
Requirement already satisfied: clickutil in /usr/local/lib/python3.7/site-packages (from blackclue) (0.0.5)
Requirement already satisfied: construct in /usr/local/lib/python3.7/site-packages (from blackclue) (2.9.45)
Requirement already satisfied: pymp4 in /usr/local/lib/python3.7/site-packages (from blackclue) (1.2.0)
Requirement already satisfied: tdx>=0.0.2 in /usr/local/lib/python3.7/site-packages (from clickutil->blackclue) (0.1.7)
Requirement already satisfied: wrapt>=1.10.8 in /usr/local/lib/python3.7/site-packages (from tdx>=0.0.2->clickutil->blackclue) (1.11.2)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/site-packages (from tdx>=0.0.2->clickutil->blackclue) (3.13)
MacBook-Pro-di-daniele:~ daniele$ blackclue -h
Traceback (most recent call last):
  File "/usr/local/bin/blackclue", line 7, in <module>
    from blackclue import dump_cli
ModuleNotFoundError: No module named 'blackclue'
MacBook-Pro-di-daniele:~ daniele$

**Comment by gandy92** [comment]
@algores Can you please try and confirm if the latest change fixes your problems?

**Comment by algores** [comment]
Hi Andi, problem is not solved, as you can see from image I tried to install your tool in a new Linux Centos 7 server but the problem still persist 

<img width="1440" alt="Screenshot 2019-10-27 00 23 22" src="https://user-images.githubusercontent.com/26186174/67626749-55ad3e80-f850-11e9-97b0-c7d712fa4ddf.png">

**Comment by gandy92** [comment]
Please note I did not update the PyPI package, yet. You can instruct pip to use the current GitHub version rather than the PyPI package by stating `https://github.com/gandy92/blackclue/archive/master.zip` instead of `blackclue`:
```
python3 -m pip install https://github.com/gandy92/blackclue/archive/master.zip
```

**Comment by algores** [comment]
Hi Andi,
there is another problem now

<img width="1165" alt="Screenshot 2019-10-27 11 00 36" src="https://user-images.githubusercontent.com/26186174/67632826-0d6e3a80-f8a9-11e9-8d9c-ce514df5e02d.png">

**Comment by gandy92** [comment]
I removed the construct dependency now, since it seems to be in conflict with the one `pymp4` requires. Does this work better now?

**Comment by algores** [comment]
Thank you very much Andi now it works with maOS 10.14.6 and Centos 7.7.1908

**Comment by gandy92** [comment]
Thank you for the feedback. I'll post a new release to PyPI the next days and if that also works, I'll close this.

**Comment by punov** [comment]
For users with M1,
`pip3 install https://github.com/gandy92/blackclue/archive/master.zip`
worked perfect for me.
